name: Deploy 
 
on: 
  release: 
    types: [published] 
  push: 
    branches: 
      - production    
  workflow_dispatch:  # Allow manual triggering 
 
permissions: 
  contents: write  # allow pushing to production branch 
 
jobs:
  fast-forward-production:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps: 
      - name: Checkout release tag 
        uses: actions/checkout@v4
        with: 
          ref: ${{ github.event.release.tag_name }} 
          fetch-depth: 0            # full history so we can push 
          persist-credentials: true # use GITHUB_TOKEN for pushes 
 
      - name: Configure Git user 
        run: | 
          git config user.name "GitHub Actions" 
          git config user.email "actions@github.com" 
 
      - name: Fast-forward production branch
        run: | 
          git push origin HEAD:production --force-with-lease

  deploy:
    runs-on: ubuntu-latest
    needs: fast-forward-production
    
    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ vars.SSH_HOST }}" >> ~/.ssh/known_hosts
 
      - name: Run deploy script on server
        run: |
          ssh ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} << 'EOF'
            set -e
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd "${{ vars.DEPLOY_PATH }}"
            ./deploy.sh
          EOF